### ISSUE TITLE
Multiple datasources created when using Spring JNDI template

### ISSUE THREAD

**Issue by sbearcsiro** [h-thurow/Simple-JNDI#5]
I'm using Simple JNDI with a third party library that uses a Spring JndiTemplate to lookup objects from JNDI.  The Spring JndiTemplate runs code like this for any JNDI operation (eg a lookup would `execute` a `JndiCallback` that ran ctx.lookup) an object:

```java
    public <T> T execute(JndiCallback<T> contextCallback) throws NamingException {
        Context ctx = getContext();
        try {
            return contextCallback.doInContext(ctx);
        }
        finally {
            releaseContext(ctx);
        }
    }
```

This is problematic as I have ~5 lookups for what is supposed to be the same connection pool and Spring causes a new Database Connection Pool to be created each time a lookup is run.

Would you approve of adding another property to disable removing contexts on close?

**Comment by h-thurow** [comment]
I am working on a new version, coming soon, that will address this problem.

**Comment by h-thurow** [comment]
Done. See [org.osjava.sj.jndi.ignoreClose](https://github.com/h-thurow/Simple-JNDI/blob/master/README.md#contextclose-and-contextdestroysubcontext)

**Comment by sbearcsiro** [comment]
@h-thurow Thanks for the change!

**Comment by mauromol** [comment]
Hello,
beware that this advertised code:

```java
Hashtable env = new InitialContext().getEnvironment();
env.remove("org.osjava.sj.jndi.ignoreClose");
env.put("java.naming.factory.initial", "org.osjava.sj.SimpleJndiContextFactory");
new InitialContext(env).close();
```

to actually close the context when the `ignoreClose` is set, does not really work. Apart from the fact that it uses an unchecked `Hashtable` (since the one returned by `getEnvironment()` is otherwise a `Hashtable<?,?>`, on which you cannot `put`), the main problem is that on the second call to the contractor of `InitialContext`, even if you pass an env without the mentioned property, the that constructor itself calls `javax.naming.InitialContext#init`, which saves into a variable named `myProps` the result of calling `ResourceManager.getInitialEnvironment(environment)` with the passed in environment. This call seems to merge the previous environment with the new one, so after this the mentioned `myProps` (which is subsequently used to initialize the context) still has `org.osjava.sj.jndi.ignoreClose` set to `true`.

I don't have any elegant solution for the unchecked access problem. For the second one, instead, the solution I found is to set `org.osjava.sj.jndi.ignoreClose` to `false`, instead of removing it from the map:

```java
@SuppressWarnings("unchecked")
Hashtable<Object, Object> env = (Hashtable<Object, Object>) new InitialContext().getEnvironment();
env.put("org.osjava.sj.jndi.ignoreClose", "false");
env.put("java.naming.factory.initial", "org.osjava.sj.SimpleJndiContextFactory");
new InitialContext(env).close();
```

In this way I was finally able to actually invalidate my context in an "aftereach" method.
